---
    - hosts: all
      become: true

      vars:
        bastion:
          user: "admin"
          host: "bastion.dev.jaylabs.io"

        rabbitmq:
          port: 5671
          management_port: 15672
          plugins:
            - rabbitmq_aws
            - rabbitmq_management
            - rabbitmq_management_agent
            - rabbitmq_stomp
            - rabbitmq_peer_discovery_common
            - rabbitmq_prometheus
          
          erlang_cookie: "****************"
          
          master_hostname: "rabbitmq-cluster-dev-node-1"
          cluster_name: "rabbitmq-cluster-dev"

          ulimit: 65536
     
      roles:
        - { role: rabbitmq }